___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column). Both 1-d and 2-d are called 'arrays'.

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [20]:
# this is a list of lists

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
# if you cast a list of lists to an array, you get a 2-d array
# 2-d as presented as output but also by bracket notations (2 set of brackets)
# 3 rows 3 columns

np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [22]:
# arange is a common way to create an array

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,2)

# start, stop, and third arg is step size

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

You can pass in a start, stop, and third number as an argument. The third number is how many numbers you want that are evenly spaced between the start and stop number.

In [5]:
np.linspace(0,10,3)

# this is a 1-d vector, and you can tell it's 1-d when there's only one 1 bracket

array([ 0.,  5., 10.])

In [31]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

Identity matrix is used for linear algebra problems which is a 2-d square matrix where number of rows matches the number of columns with a diagonal of 1s while the rest are 0s. 

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [47]:
# ".rand" is a method 

np.random.rand(2)

# it will create an array of the given shape you pass in and will populate it
# with random samples from uniform distribution from 0 to 1
# the result will be 1-dimensional

array([ 0.11570539,  0.35279769])

In [7]:
np.random.rand(5)

array([0.20411576, 0.89440587, 0.31419347, 0.05473751, 0.74483745])

In [8]:
np.random.rand(5,5)

# the second argument is dimensions (in this case, 5 by 5)

array([[0.64804941, 0.28642231, 0.17429965, 0.14402978, 0.25540909],
       [0.99242446, 0.92468813, 0.36802047, 0.64099523, 0.50616311],
       [0.81822037, 0.14470394, 0.81727569, 0.08193315, 0.63750131],
       [0.70035422, 0.37884825, 0.74969128, 0.7330231 , 0.66341772],
       [0.27469552, 0.80874195, 0.83795521, 0.34676045, 0.04856624]])

In [17]:
np.random.rand(3,4) 

# in this case is 3 rows, 4 columns

array([[0.28074063, 0.19005765, 0.20327163, 0.77881716],
       [0.37803205, 0.74411563, 0.94858031, 0.57502497],
       [0.88705961, 0.9201566 , 0.05133304, 0.89100008]])

### randn

Return a sample (or samples) from the "standard normal" (or Gaussian) distribution. Rand is uniform whereas Randn will not return numbers from an uniform distribution from 0 to 1, but instead from a standard normal distribution centered around 0. 

In [48]:
np.random.randn(2)

# we get 2 random numbers from a standard normal distribution

array([-0.27954018,  0.90078368])

In [18]:
np.random.randn(4,5)

array([[-0.81490497, -0.09443668, -0.37738043,  0.85654486,  0.22508481],
       [ 0.79997125,  1.32531389, -0.07403582,  0.38100825, -0.39093336],
       [-1.50080844,  0.53495054,  2.21504983, -1.12324293,  0.58912282],
       [ 0.30588434, -1.04951403,  2.7989043 , -0.53269451,  1.39243623]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [50]:
np.random.randint(1,100)

44

In [51]:
np.random.randint(1,100,10)

# the arguments are a low, a high, and size/how big you want your 1-d vector
# "1" is inclusive, but "100" is exclusive, so to include "100", it'll need 
# to be "101"

array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [19]:
arr = np.arange(25) # we have 25 elements in this array

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0,50,10)

# 10 integers random of 0-49 (not including 50)
# there can be 2 of the same numbers repeating like "33, 33, 43, 43", etc.

In [41]:
ranarr

array([37, 33, 43, 36, 19, 30, 41, 25, 17, 29])

## Reshape
Returns an array containing the same data with a new shape.

In [44]:
arr.reshape(5,5) 

# you will need to makre sure you have enough elements to fill 5 by 5 or
# you will get an error
# arr originally had 25 elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
# example of error below:

arr.reshape(5,20)

# 5 x 20 = 100 elements, and "arr" only had 25 elements

ValueError: cannot reshape array of size 25 into shape (5,20)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [64]:
ranarr

# random array defined above from "ranarr = np.random.randint(0,50,10)"

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [61]:
ranarr.max()

# this will return the max value of the array

49

In [62]:
ranarr.argmax()

# this is the location of the max value of the array
# meaning, the 4th index is where the "49" is or the max-value in the array

4

In [63]:
ranarr.min()

# return minimum value of array

2

In [60]:
ranarr.argmin()

# index location of the minimum value 

5

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector
arr.shape

# 25 comma, means 1-d vector

# why does the shape of the array matter?

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype

# returns the datatype of the array

dtype('int64')

# Great Job!