___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
# solution shows: 
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
arr = np.arange(0,11.0)
arr[:] = 0
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
# solution:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
arr2 = np.arange(0,11.0)
arr2[:] = 1
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [119]:
#solution 

np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [120]:
# you can also do

np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [29]:
arr3 = np.arange(0,11.0)
arr3[:] = 5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [39]:
arr5 = np.arange(10,51)
is_even_arr5 = arr5%2==0
arr5[is_even_arr5]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [83]:
# solution shows:

np.arange(10,51,2)

# argument is start, stop, step size

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [121]:
# solution shows:
np.arange(9).reshape(3,3)

# arange(9) implies (0,9)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
three_by_three = np.arange(0,9).reshape(3,3)
three_by_three

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [42]:
np.eye(3)

# identity matrix must be squared

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [45]:
np.random.rand(1)

array([0.93980583])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [50]:
np.random.randn(25)

# .randn is a standard distribution

array([ 0.07016858,  1.05148823, -0.88505145,  0.04949424,  0.4660623 ,
       -1.89642462, -0.57362016,  0.76332221,  0.58573245,  0.17551322,
       -0.99532591, -0.1926605 ,  1.32021938,  1.0814355 ,  0.45531163,
       -0.04513313, -0.65277913, -0.00429514,  0.36178847, -0.1099749 ,
        1.2778418 , -0.29213359,  0.67071545, -0.58605245, -0.73734827])

In [122]:
np.random.randn(25).shape

# it's a 1 line matrix of 25

(25,)

#### Create the following matrix:

In [35]:
# solution shows: 

np.arange(1,101).reshape(10,10)/100

# this is 2-d matrix

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [123]:
# solution also includes using linspace: 

np.linspace(0.01,1,100).reshape(10,10)

# linspace is start, stop, and 100 steps

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [78]:
ten_by_ten = np.arange(0.01,1.01,0.01)
ten_by_ten = ten_by_ten.reshape(10,10) # reshaping it will not make save the format as that so we need to reassign the variable
# to the original variable
ten_by_ten

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [80]:
# example below of when not assigning the variable and what happens: 

ten_by_ten = np.arange(0.01,1.01,0.01)
ten_by_ten.reshape(10,10)
ten_by_ten

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [81]:
ten_by_ten = np.arange(0.01,1.01,0.01)
ten_by_ten.reshape(10,10) 

# but this display/view is reshaped properly

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [82]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
# problem 1 

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [94]:
# solution says
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [41]:
#p problem 2

20

In [95]:
mat[3][4]

20

In [96]:
# display the array "mat" again

mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
# problem 3
# this is a 3 by 1 matrix


array([[ 2],
       [ 7],
       [12]])

In [100]:
# the solution says:

# we need to use ":" slice notation between "1" and "2"

mat[:3,1:2]

# the format is array[row,column] or array[row][column]
# the colon means from where to where
# ":3" means from start to 3rd row BUT NOT INCLUDING THIRD ROW
# "1:" means from 1st column to onward
# ":2" means up to 2nd column but not including 2nd column
# "1:2" means 1st column up until but not including 2nd column

array([[ 2],
       [ 7],
       [12]])

In [126]:
# if you want double brackets and not single ones like below, you will need to specify the ":" slice notation

mat[:3,1] 

# you can see below, without "1:2", it's single brackets and formatted incorrectly

array([ 2,  7, 12])

In [46]:
# problem 4

array([21, 22, 23, 24, 25])

In [101]:
mat[4]

# entire 4th row

# the solution shows:

mat[4,:]

array([21, 22, 23, 24, 25])

In [127]:
mat[-1,:]

# if you know it's the last row, you can do "-1"

array([21, 22, 23, 24, 25])

In [49]:
# problem 5

# there is double brackets which means we need to use slice notation of "3:5"

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [102]:
mat[3:5]

# entire 3rd row, plus 4th row, not including 5th row

# solution says:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [103]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

325

In [108]:
mat.sum()

325

In [128]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

7.2111025509279782

In [109]:
mat.std()

7.211102550927978

In [129]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

In [110]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [134]:
np.sum(mat, axis=0)

# "axis" is an argument 
# the documentation says, "return the sum of the array elements over hte given axis"

array([55, 60, 65, 70, 75])

In [116]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [117]:
mat.sum(axis=2)

# "axis" only has "0" or "1"

AxisError: axis 2 is out of bounds for array of dimension 2

# Great Job!